spring:

    profiles:
        active: dev

    liquibase:
        enabled: ${APP_LIQUIBASE_ENABLED:false}
#Configure liquibase default changelog
        change-log: classpath:db/changelog/liquibase-changeLog.xml
    hibernate:
        cache:
#Enable 2level cache hibernate
            use_second_level_cache: true
            region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            
server:
    port: ${PORT:8080}
    
logging:
    level:
        org.springframework.web: DEBUG
        soft.samarone.testeV1.web.rest: DEBUG

#ip:
#    client:
#        fixed: 8.8.8.8 # para testes apenas
#    loopback:
#        fixed: 172.17.0.1 # para testes apenas