spring:
    liquibase:
#Configure liquibase default changelog
        change-log: classpath:db/changelog/liquibase-changeLog.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:gf;DB_CLOSE_DELAY=-1
        name:
        username:
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        open-in-view: false
        show-sql: false
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    hibernate:
        cache:
#Enable 2level cache hibernate
            use_second_level_cache: true
            region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            
server:
    port: ${PORT:8080}

#ip:
#    client:
#        fixed: 8.8.8.8 # para testes apenas
#    loopback:
#        fixed: 172.17.0.1 # para testes apenas
