spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:gf;DB_CLOSE_DELAY=-1
        name:
        username:
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        open-in-view: false
        show-sql: false
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false