spring:
    liquibase:
        enabled: ${APP_LIQUIBASE_ENABLED:false}
#Configure liquibase default changelog
        change-log: classpath:db/changelog/liquibase-changeLog.xml
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:${SPRING_DATASOURCE_URL}?createDatabaseIfNotExist=true
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
            show-sql: false
            database: postgresql
            database-platform: org.hibernate.dialect.PostgreSQL9Dialect
            open-in-view: false
            generate-ddl: false
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    hibernate:
        cache:
#Enable 2level cache hibernate
            use_second_level_cache: true
            region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
            
server:
    port: ${PORT:8080}
    
logging:
    level:
        org.springframework.web: DEBUG
        soft.samarone.testeV1.web.rest: DEBUG

#ip:
#    client:
#        fixed: 8.8.8.8 # para testes apenas
#    loopback:
#        fixed: 172.17.0.1 # para testes apenas
