spring:

    profiles:
        active: local

# Database
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://172.17.0.1:5432/testev1_dev?createDatabaseIfNotExist=true
        username: admin
        password: 123mudar
# JPA properties
    jpa:
        hibernate:
          ddl-auto: none
          show-sql: true
          database: postgresql
          database-platform: org.hibernate.dialect.PostgreSQLDialect
          open-in-view: false
          generate-ddl: false
