spring:
    liquibase:
#Configure liquibase default changelog
        change-log: classpath:db/changelog/liquibase-changeLog.xml
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:gf;DB_CLOSE_DELAY=-1
        name:
        username:
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        open-in-view: false
        show-sql: true
    hibernate:
        cache:
#Enable 2level cache hibernate
            use_second_level_cache:true
                region.factory_class:org.hibernate.cache.ehcache.EhCacheRegionFactory
#            ddl-auto: none
#            naming:
#                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        properties:
#            hibernate.id.new_generator_mappings: true
#            hibernate.cache.use_second_level_cache: false
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: true
#            hibernate.hbm2ddl.auto: validate
server:
    port: ${PORT:8080}
